
export const metadata = {
  title: 'About Page',
  description: 'Generated by Next.js',
}

export default function AboutLayout({children,}: {children: React.ReactNode}) {
  return (
    <>


        <h1>Soy el layout de /about</h1>
      
        {children}



    </>
  )
}
