import Navbar from "../../components/navbar"
import {Roboto} from "next/font/google"

//Asi se exportan los metadatos
export const metadata = {
  title: 'Home Page',
  description: 'Generated by Next.js',
  keywords: "asd, asd1, asd2"
}
//

const roboto = Roboto({
  weight: ["300","400","700"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>


        <Navbar/>
      
        {children}


      </body>
    </html>
  )
}
